### PR TITLE
Get tokens and their icons from IPFS instead of Kyber/TrustWallet defaults, Bootstrap JS/CSS from IPFS

### LINKED ISSUE #35: Get tokens from IPFS instead of Kyber defaults

### PR DESCRIPTION
**Pull request by danimesq**
Makes it more decentralized, and enables adding new tokens.

Signed-off-by: Daniell Mesquita <daniellmesquita@protonmail.com>

### CODE REVIEW

**Comment by danimesq** [comment]
In this case, why Dat instead of IPFS: can transparently update tokens list, without uploading a whole file for just changing a few characters.

**Comment by hilmarx** [comment]
@DaniellMesquita How do you ensure that the list of tokens taken from ```https://tokens.hashbase.io/currencies.json``` reflect the tokens tradeable on Kyber Network? There should not be any additional tokens in the feed that result in reverted tx on a smart contract level. An idea to make it even more decentralized would be to integrate IPFSWAP into Uniswap, which has permissionless token adding capabilities.

**Comment by danimesq** [comment]
> How do you ensure that the list of tokens taken from https://tokens.hashbase.io/currencies.json reflect the tokens tradeable on Kyber Network?

The only thing is keeping it as-is, and only adding new tokens when Kyber announces it. I'll undo the new added tokens. So, only Kyber can add its new tokens?

**Comment by danimesq** [comment]
Using IPFS instead of Dat.
Now, Kyber token list is static and more trustworthy than getting it from Kyber server.
I don't think it adds new tokens so often. When new token is add, just update its address.

**Comment by danimesq** [comment]
@hilmarx

**Comment by hilmarx** [comment]
Screenshot 2019-11-05 at 21 35 54


fetching icons from IPFS does not work ```"GET /stylesheets/searchicon.png HTTP/1.1" 404 -```

**Comment by danimesq** [comment]
@hilmarx 
From which address? IPFS?
Here it works.
image
image

**Comment by danimesq** [comment]
@hilmarx
Is yet getting this error? It works in any test.

**Review by hilmarx — APPROVED** [review]

**Comment by hilmarx** [comment]
had a bad connection, IPFS seems to have problems then, but it worked when I tested it now.

**Pull request merged**
